apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: restaurantservice
  name: restaurantservice
spec:
  ports:
    - name: "3020"
      port: 3020
      targetPort: 3020
  selector:
    io.kompose.service: restaurantservice
status:
  loadBalancer: {}
